spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_dev
    username: micro
    password: micro
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
  jmx:
    enabled: false
logging:
  level:
    org.flywaydb: DEBUG
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.hibernate: DEBUG
#    com.dp.authservice: DEBUG
