spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_dev
    username: micro
    password: micro
  jpa:
    properties:
      hibernate:
        ddl-auto: none
logging:
  level:
    org.flywaydb: INFO
#    root: INFO
#    org.springframework.web: INFO
#    org.hibernate: WARN
#    com.dp.authservice: INFO